import { create } from 'xmlbuilder2';

export default function buildCustomerXML(customer) {
  return create({ version: '1.0' })
    .ele('ENVELOPE')
      .ele('HEADER')
        .ele('TALLYREQUEST').txt('Import Data').up()
      .up()
      .ele('BODY')
        .ele('IMPORTDATA')
          .ele('REQUESTDESC')
            .ele('REPORTNAME').txt('All Masters').up()
          .up()
          .ele('REQUESTDATA')
            .ele('TALLYMESSAGE').att('xmlns:UDF', 'TallyUDF')
              .ele('LEDGER')
                .att('NAME', customer.customerName)
                .att('Action', 'Create')
                .ele('PARENT').txt('Sundry Debtors').up()
                .ele('MAILINGNAME.LIST')
                  .ele('MAILINGNAME').txt(customer.customerName).up()
                .up()
                .ele('EMAIL').txt(customer.companyEmail || '').up()
                .ele('PARTYGSTIN').txt(customer.gstNumber || '').up()
                .ele('COUNTRYNAME').txt(customer.country || 'India').up()
                .ele('STATE').txt(customer.state || 'Karnataka').up()
                .ele('GSTREGISTRATIONTYPE').txt('Regular').up()
                .ele('GSTAPPLICABLE').txt('Applicable').up()
                .ele('ISBILLWISEON').txt('Yes').up()
                .ele('ISDEEMEDPOSITIVE').txt('Yes').up()
                .ele('OPENINGBALANCE').txt('0.00').up()
                .ele('PARTYTYPE').txt('Customer').up()
                .ele('ADDRESS.LIST')
                  .ele('ADDRESS').txt(customer.customerBillingAddress || '').up()
                .up()
                .ele('LANGUAGENAME.LIST')
                  .ele('LANGUAGENAME')
                    .ele('NAME.LIST')
                      .ele('NAME').txt('English').up()
                    .up()
                    .ele('LANGUAGEID').txt('1033').up()
                  .up()
                .up()
              .up()
            .up()
          .up()
        .up()
      .up()
    .end({ prettyPrint: true });
}
